/first_node:
  ros__parameters:
    _onenode_queue_parameter: 15
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    timer_parameter: 2
    use_sim_time: false

